apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sparrow-web
  name: sparrow-web
spec:
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  selector:
    matchLabels:
      app: sparrow-web
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sparrow-web
    spec:
      containers:
        - image: sparrowprod.azurecr.io/sparrow-web:_BUILD__ID_
          name: sparrow-web
          imagePullPolicy: Always
          ports:
            - containerPort: 1422
          resources:
            requests:
              cpu: 100m
              memory: 600Mi
            limits:
              cpu: 500m
              memory: 700Mi

          # livenessProbe:
          #   tcpSocket:
          #     port: 1422
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          #   successThreshold: 1
          # readinessProbe:
          #   tcpSocket:
          #     port: 1422
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 5
            # failureThreshold: 3
            # successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: sparrow-web
  labels:
    run: sparrow-web
spec:
  type: ClusterIP
  selector:
    app: sparrow-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1422