name: Development release

on:
  push:
    branches:
      - development

env: 
    VITE_API_URL: ${{ secrets.VITE_API_URL_DEV }}
    VITE_MIX_PANEL_TOKEN: ${{ secrets.VITE_MIX_PANEL_TOKEN }}
    VITE_ENABLE_MIX_PANEL: ${{ secrets.VITE_ENABLE_MIX_PANEL }}
    VITE_API_TIMEOUT: ${{ secrets.VITE_API_TIMEOUT }}
    VITE_SPARROW_SUPPORT_EMAIL: ${{ secrets.VITE_SPARROW_SUPPORT_EMAIL }}
    VITE_AUTH_URL: ${{ secrets.VITE_AUTH_URL_DEV }}

jobs:
  release_win:
    runs-on: windows-latest

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Windows SDK
        run: Invoke-WebRequest -Uri https://aka.ms/winsdk/10/latest/SdkSetup.exe -OutFile $env:TEMP\SdkSetup.exe
        shell: powershell

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Build Tauri App
        run: |
          $TAURI_SIGNING_PRIVATE_KEY="${{ secrets.TAURI_PRIVATE_KEY }}"
          $TAURI_SIGNING_PRIVATE_KEY_PASSWORD="${{ secrets.TAURI_KEY_PASSWORD }}" 
          yarn cache clean
          npm install -g pnpm
          yarn install
          yarn tauri build --debug
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}

      - name: msi sig
        run: Get-Content D:\a\sparrow-app\sparrow-app\src-tauri\target\debug\bundle\msi\*.sig
  
      - name: nsis sig
        run: Get-Content D:\a\sparrow-app\sparrow-app\src-tauri\target\debug\bundle\nsis\*.sig

      - name: sign msi
        run: |
           $cert = New-SelfSignedCertificate -Subject "CN=Certificate" -CertStoreLocation "Cert:\LocalMachine\My" -KeyUsage DigitalSignature -Type CodeSigningCert -KeySpec Signature -NotAfter (Get-Date).AddDays(90)
           $certPath = "Cert:\LocalMachine\My\$($cert.Thumbprint)"
           $password = ConvertTo-SecureString -String "sparrow123" -Force -AsPlainText
           Export-PfxCertificate -Cert $certPath -FilePath "D:\a\sparrow-app\sparrow-app\src-tauri\target\debug\bundle\Certificate.pfx" -Password $password
           & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x86\SignTool.exe" sign /f "D:\a\sparrow-app\sparrow-app\src-tauri\target\debug\bundle\Certificate.pfx" /p sparrow123 /tr http://timestamp.digicert.com /td sha256 /fd sha256 /v "D:\a\sparrow-app\sparrow-app\src-tauri\target\debug\bundle\msi\*.msi"
      

      - name: Upload win updater to Azure Blob Storage
        run: |
          az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --container-name ${{ secrets.AZURE_CONTAINER_NAME }} --file D:\a\sparrow-app\sparrow-app\src-tauri\target\debug\bundle\msi\Sparrow_0.0.0_x64_en-US.msi.zip --name Sparrow_0.0.0_x64_en-US.msi.zip --overwrite
        env:
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
           
      - name: Install App Center CLI
        run: |
          npm install -g appcenter-cli@latest
      - name: Log in to App Center
        run: appcenter login --token ${{ secrets.APPCENTER_API_TOKEN }}

      - name: Get PR Branch Name
        id: pr_branch
        run: echo "::set-output name=branch::${{ github.head_ref }}"
        
      - name: var
        run: |
          $branch_name = "${{ steps.pr_branch.outputs.branch }}"
          echo "Branch Name: $branch_name"
      
      - name: Upload to App Center
        run: |
          appcenter login --token ${{ secrets.APPCENTER_API_TOKEN }}
          $branch_name = "${{ steps.pr_branch.outputs.branch }}"
          echo "Branch Name: $branch_name"
          appcenter distribute release -f D:\a\sparrow-app\sparrow-app\src-tauri\target\debug\bundle\msi\Sparrow_0.0.0_x64_en-US.msi -g Collaborators --app techdome/Sparrow --build-version "branch-$branch_name" --build-number ${{ github.run_number }}
      
      - name: status check and upload
        uses: neonidian/teams-notify-build-status@v3
        if: always()
        with:
          webhookUrl: |
           ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
          message: |
            ðŸš€ **Build Status Update** ðŸš€
            The workflow (sparrow-app for windows) has completed with status: **${{ job.status }}**.
            ðŸ‘‰ Check it out latest release here [AppCenter](https://appcenter.ms/users/techdome/apps/Sparrow)!
          titleBackgroundColor: ${{ job.status }}
        env:
          SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true


  release_macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: '20.8'

      - name: Build Tauri App
        run: |
          TAURI_SIGNING_PRIVATE_KEY="${{ secrets.TAURI_PRIVATE_KEY }}"
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD="${{ secrets.TAURI_KEY_PASSWORD }}" 
          APPLE_SIGNING_IDENTITY="${{ secrets.APPLE_SIGNING_IDENTITY }}"
          APPLE_CERTIFICATE="${{ secrets.APPLE_CERTIFICATE }}"
          APPLE_CERTIFICATE_PASSWORD="${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" 
          yarn install
          yarn tauri build --debug
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
      
      - name: file content
        run: cat /Users/runner/work/sparrow-app/sparrow-app/src-tauri/target/debug/bundle/macos/*.sig
      
      - name: Upload mac updater to Azure Blob Storage
        run: |
          az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --container-name ${{ secrets.AZURE_CONTAINER_NAME }} --file /Users/runner/work/sparrow-app/sparrow-app/src-tauri/target/debug/bundle/macos/Sparrow.app.tar.gz --name Sparrow.app.tar.gz --overwrite
        env:
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}

      - name: Install App Center CLI
        run: |
          npm install -g appcenter-cli@latest

      - name: Get PR Branch Name
        id: pr_branch
        run: echo "::set-output name=branch::$(echo ${{ github.head_ref }})"

      - name: Upload to App Center
        run: |
          appcenter login --token ${{ secrets.APPCENTER_API_TOKEN }}
          branch_name="${{ steps.pr_branch.outputs.branch }}"
          echo "Branch Name: $branch_name"
          appcenter distribute release -f /Users/runner/work/sparrow-app/sparrow-app/src-tauri/target/debug/bundle/dmg/*.dmg -g Collaborators --app techdome/Sparrow-1 --build-version branch-${branch_name} --build-number ${{ github.run_number }}
      - name: status check and upload
        uses: neonidian/teams-notify-build-status@v3
        if: always()
        with:
          webhookUrl: |
            ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
          message: |
            ðŸš€ **Build Status Update** ðŸš€
            The workflow (sparrow-app for **Mac**) has completed with status: **${{ job.status }}**.
            ðŸ‘‰ Check it out latest release here [AppCenter](https://appcenter.ms/users/techdome/apps/Sparrow-mac)!
          titleBackgroundColor: ${{ job.status }}
        env:
          SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
