name: Mac Build, Sign, and Download Tauri App 

on:
  push:
    branches:
      - development

env: 
 VITE_API_URL: ${{secrets.VITE_API_URL}}
 VITE_MIX_PANEL_TOKEN: ${{secrets.VITE_MIX_PANEL_TOKEN}}
 VITE_ENABLE_MIX_PANEL: ${{secrets.VITE_ENABLE_MIX_PANEL}}


jobs:
  build_and_sign:
    runs-on: macos-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable

    # - name: Rust cache
    #   uses: swatinem/rust-cache@v2
    #   with:
    #     workspaces: './src-tauri -> target'

    - name: Sync node version and setup cache
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        #cache: 'yarn' # Set this to npm, yarn or pnpm.

    - name: Install Dependencies
      run: |
        yarn install
        yarn tauri build --debug

    - name: Build Tauri App
      run: |
        APPLE_SIGNING_IDENTITY="${{ secrets.APPLE_SIGNING_IDENTITY }}"
        APPLE_CERTIFICATE="${{ secrets.APPLE_CERTIFICATE }}"
        APPLE_CERTIFICATE_PASSWORD="${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" yarn tauri build --debug

    # - name: Archive and Sign App
    #   run: |
    #     zip -r sparrow-app.app.zip target/release/sparrow-app.app
    #     codesign --force --verify --verbose --sign "$APPLE_SIGNING_IDENTITY" target/release/YourAppName.app

    - name: Archive
      run: |
        #zip -r sparrow.app.zip /Users/runner/work/sparrow-app/sparrow-app/src-tauri/target/debug/bundle/macos/sparrow-app.app
        #codesign --force --verify --verbose --sign "$APPLE_SIGNING_IDENTITY" target/debug/bundle/macos/sparrow-app.app
        zip -r sparrow-app_0.0.0_x64.dmg /Users/runner/work/sparrow-app/sparrow-app/src-tauri/target/debug/bundle/dmg/sparrow-app_0.0.0_x64.dmg

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sparrow-macos
        path: |
          sparrow.app.zip
          sparrow-app_0.0.0_x64.dmg
    
    - name: Install App Center CLI
      run: |
        npm install -g appcenter-cli@latest

    - name: Upload to App Center
      run: |
        appcenter login --token ${{ secrets.APPCENTER_API_TOKEN_MAC }}
        appcenter distribute release -f /Users/runner/work/sparrow-app/sparrow-app/src-tauri/target/debug/bundle/dmg/sparrow-app_0.0.0_x64.dmg -g Collaborators --app Techdome/Sparrow-1 --build-version v12.23.${{ github.run_number }} --build-number ${{ github.run_number }}

    - name: status check and upload
      uses: neonidian/teams-notify-build-status@v3
      if: always()
      with:
        webhookUrl: |
          ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
        message: |
          ðŸš€ **Build Status Update** ðŸš€

          The workflow (sparrow-app for **Mac**) has completed with status: **${{ job.status }}**.

          ðŸ‘‰ Check it out latest release here [AppCenter](https://appcenter.ms/users/techdome/apps/Sparrow-1)!
        titleBackgroundColor: ${{ job.status }}
      env:
        SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
